### ISSUE TITLE
Interesting setup.

### ISSUE THREAD

**Issue by KyleCotton** [nanzhong/env#2] opened 2020-05-05 13:50 UTC
Nanzhong, I was just looking at another one of your repos and stumbled across this one. It looks very interesting.

- Do you use something like `terminus` over ssh on the iPad to connect to the droplet?
- I'm guessing its strictly CLI?
- What are the advantages of this setup?

Thanks for the insight.

**Comment by nanzhong** [comment] 2020-06-12 04:19
Yup, I use https://github.com/blinksh/blink on my iPad, and my workflow is indeed all terminal based.

There are some obvious benefits to having a portable and reproducible environment that are independent to my iPad setup, but I'll try and list a few of the big ones specific to the iPad here:

*Pros:*
- Basically don't need to worry about battery life ever again. On my macbook pro, running docker + a kubernetes cluster for local dev basically means I only get a few short hours of battery life.
- LTE is great, internet access without having to think about connecting is actually much more valuable than it sounds.
- iPad hardware and software is incredible. You don't realize how fast and snappy things are until you go back to anything else (in my case my macbook pro when I occasionally need it).
- I also use my iPad for drawing, diagraming, photo editing, and all those workflows on the iPad are amazing.
- Easily replaceable. This is actually what started me down the road of seriously thinking about portable development envs. My partner accidentally spilt tea over my macbook pro the week we were rushing to try and launch the early access to [DigitalOcean Kubernetes Service](https://www.digitalocean.com/products/kubernetes/), and built to order machines take way too long to replace.

*Cons:*
- Copy and paste, transferring files, etc. are all very painful. I've had to write tools to make this more bearable.
- With iPadOS things got a lot better, but there are still many websites, that just don't work.
- Just can't do some things that are possible with a real machine (eg. I still need to use my macbook for browser dev tools, building images for my raspberry pi, etc.).
- No internet access greatly limits what can be done (this is the reason I bring my raspberry pi around with me, I can plug it in to my iPad and work on that when I don't have internet).
- Camera is only active when the app using it is in the foreground. This means for google meet/hangouts or other video apps like zoom, you can't really multi task.

**Closed as completed** 2020-07-10 14:58 UTC
